### ISSUE TITLE
how can i use this library?

### ISSUE THREAD

**Issue by bryce0516** [jerson/react-native-fast-rsa#19]
there is no example.

i'm using expo framework, this library looks so good.

import RSA from "react-native-fast-rsa";

const somenamefunction = async () => {
const result = await RSA.generate(512) 
console.log(result)
}
in useeffect and onPress 
is not working. did i some thing wrong?

**Comment by jerson** [comment]
hi @bryce0516 thanks for the question, unfortunately we dont support expo right now, you will need to eject from expo in order to use this library

reference: https://docs.expo.dev/workflow/using-libraries/

**Comment by bryce0516** [comment]
Thanks! Unfortunately, I can't eject this project due to customer's requirement. But if the day comes when RSA module is needed, I'll use it. looks Good. Have a nice day!
