### ISSUE TITLE
Update repo with latest version of rsa-mobile

### ISSUE THREAD

**Issue by sabhatdocai** [jerson/react-native-fast-rsa#2]
is this repo using the latest version of rsa-mobile

`static encryptOAEP(message: string, label: string, hashName: RSAHash, pkcs12: string, passphrase: string): Promise<string>;`

the latest rsa-mobile code doesn't not seem to have the passphrase? 

Can you additionally add some example call specifically for the above mentioned function?

we get the following error when we pass the public RSA key to the function

`pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2" UserInfo={NSLocalizedDescription=pkcs12: error reading P12 data: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2}`

Thanks

**Comment by jerson** [comment]
hi @sabhatdocai yes, you are right, im gonna update to use only public and private keys here

note: at this moment this version requires a pkcs12 and not a private key.

**Comment by jerson** [comment]
hi @sabhatdocai please can you try latest version i updated to latest rsa-mobile

https://www.npmjs.com/package/react-native-fast-rsa

**Comment by sabhatdocai** [comment]
@jerson 
Thanks for the update. Works fine now.
