### ISSUE TITLE
Windows build error try with development mode and with admin previlages did not work

### ISSUE THREAD

**Issue by kprabath** [jerson/react-native-fast-rsa#20]
`* What went wrong:
Execution failed for task ':react-native-fast-rsa:generateJsonModelDebug'.
> D:\Private\React-Native\test\node_modules\react-native-fast-rsa\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at D:\Private\Reac
t-Native\test\node_modules\react-native-fast-rsa\android\CMakeLists.txt:14 (add_library):
    Syntax error in cmake code when parsing string

      D:\Private\React-Native\test\android/../node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\P'.`

**Comment by jerson** [comment]
Hey @kprabath thanks for report the issue I haven't test this library in Windows before, im gonna test locally this week

**Comment by jerson** [comment]
hey @kprabath i just fixed this issue, please use https://www.npmjs.com/package/react-native-fast-rsa/v/2.0.1

ref https://github.com/jerson/react-native-fast-rsa/commit/0966539f71c7faff51ac4c1e0820547383b142ee
