### ISSUE TITLE
Android not able to open app in debug mode

### ISSUE THREAD

**Issue by AshishMall** [jerson/react-native-fast-rsa#24]
Hi, I am not able to open app debug mode in android when I start debugging in the app, app automatically close but it works fine when I disable debug mode and also works fine in ios debug mode and without debug mode. can you please help me find the solution

**Comment by AshishMall** [comment]
any update on this issue , if you have then please udpate

**Comment by jerson** [comment]
Hi, maybe is too late but I just fixed https://www.npmjs.com/package/react-native-fast-rsa/v/2.3.4
