### ISSUE TITLE
[TypeError: null is not an object (evaluating 'FastRSANativeModules.call')]

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [jerson/react-native-fast-rsa#28]
I tries this in react native with expo and I got this exception in calling

`const keys = await RSA.generate(2048)`

Is it possible to use in expo or will you provide the support for it.
Waiting for your response

**Comment by jerson** [comment]
Hi @ArjunPatidar-numero thanks for report the issue, currently we don't support expo, so in order to use this library you need to eject first

**Comment by obie3** [comment]
Hi @jerson I encountered the same error message, on an ejected expo project after executing pod install to auto-link  other dependencies, please what  could I be missing
