### ISSUE TITLE
docs: you need admin privs on windows to install

### ISSUE THREAD

**Issue by davidcallanan** [jerson/react-native-fast-rsa#4]
On windows it appears that you need admin privileges to install this package, I suggest you add a note about that to the readme. This appears to be because symlinks require admin privileges on Windows.

**Comment by jerson** [comment]
hi @davidcallanan,  thanks for report the issue,  maybe is too late... but admin is not needed, only developer mode in order to use symlinks

**Comment by jerson** [comment]
updated readme
