### ISSUE TITLE
Error with react-native link

### ISSUE THREAD

**Issue by davidcallanan** [jerson/react-native-fast-rsa#5]
I try to run `react-native link react-native-fast-rsa` and I get the following error. If I instead ignore the error and try to `react-native run-android` I get the same error come up again.

```
error EPERM: operation not permitted, scandir 'C:/path/to/react-native-app/node_modules/react-native-fast-rsa/ios/Rsa.framework/Headers'.
```

This is preventing me from running my application and from using this package.

 - OS: windows
 - Node.js v14.7.0

**Comment by davidcallanan** [comment]
It looks like this might be a problem with how `extract-zip` is extracting `Rsa.frameworks.zip`.

`Headers` ends up being a symlink (I'm not sure if that's intended) and when I attempt to "open file location" on the symlink there are permission errors and I can't seem to grant myself permission correctly.

**I deleted `Rsa.frameworks/` and manually extracted the zip file using 7Zip**. The resulting `Headers` file and other files are no longer symlinks. I don't know if this is the correct behaviour or not, but regardless, this was enough to successfully run `react-native link react-native-fast-rsa`.

I can't test iOS at the moment so I don't know if this temporary solution would cause problems. Presumably you can't develop iOS on Windows anyway, and this is likely a windows-only issue, so I'm probably ok.

**Comment by jerson** [comment]
Hi @davidcallanan, thanks for reporting the issue, you are right I have never used the library in windows, only in linux and macOS, these days I will try to see what issues can be fixed

**Comment by davidcallanan** [comment]
Hi @jerson , everything seems to be working fine anyway, thanks very much for making this package, this was the only one I could find!
