### ISSUE TITLE
library 'react-native-fast-rsa' not found

### ISSUE THREAD

**Issue by saumyabhatnagar2000** [jerson/react-native-fast-rsa#72]
Attempting to build for ios with Xcode 15  fails, with error `library 'react-native-fast-rsa' not found`.
The build is successful for android.
The build get successful when I remove `react-native-fast-rsa`.
Are there any other installation steps for ios?

**Comment by neel132** [comment]
any update on this ?

Even I am facing this issue on-
M2 Chip
Xcode - 15.0

Bare react-native - 0.68

**Comment by jerson** [comment]
Hi, thanks for report this issue, going to take a look today

**Comment by jerson** [comment]
hi @saumyabhatnagar2000 , @neel132 could you try with this branch please https://github.com/jerson/react-native-fast-rsa/pull/73

**Comment by saumyabhatnagar2000** [comment]
Still not working for me. @neel132 did it work for you?

**Comment by neel132** [comment]
It is still the same error for me as well @saumyabhatnagar2000 @jerson .
Even the example project has same error.

Reference -

![Screenshot 2023-10-04 at 5 31 42 PM](https://github.com/jerson/react-native-fast-rsa/assets/106615630/2beebfa8-2eb0-4230-b8ad-40684f86a8b6)

**Comment by jerson** [comment]
I see, so it seems is related to arm64 slice, let me try something different today, thanks for the patient

**Comment by jerson** [comment]
hey @saumyabhatnagar2000 , @neel132  sorry for the delay, I updated podspec, could you try one more time please

make sure the pod spec looks like this one
https://github.com/jerson/react-native-fast-rsa/pull/73/files#diff-adbac605057eb9b22b0847a0e2e3f269c1038d1998e332e5cce54a8df3333f88L21-L23

**Comment by saumyabhatnagar2000** [comment]
`Building for 'iOS-simulator', but linking in object file (/node_modules/react-native-fast-rsa/ios/librsa_bridge.a[arm64][2](go.o)) built for 'iOS'`

Getting this error

This is my pod spec file.
Let me know if I am missing something @jerson 
<img width="831" alt="Screenshot 2023-10-06 at 3 39 55 PM" src="https://github.com/jerson/react-native-fast-rsa/assets/97280523/150fdee7-0ea7-4a52-abb1-988c6c0203d1">
