### ISSUE TITLE
[M1] The app hangs on the splash screen when trying to run on iOS simulator on Mac M1

### ISSUE THREAD

**Issue by DominikHinc** [jerson/react-native-fast-rsa#86]
As in the title, when trying to run the app on iOS simulator on Mac M1 the app freezes on splash screen. No error message, no crash, just freeze. When running on a real iPhone device everything seems to be working fine. This is true for the Example app in this repo.

**Comment by jerson** [comment]
Hi @DominikHinc  thanks for report this issue, I don't have an M1/M2 device to debug this, could you send me details about which react native and library version you are using, that may give me an idea how to debug this

**Comment by jerson** [comment]
Hi, this should be fixed in the newest version https://www.npmjs.com/package/react-native-fast-rsa/v/2.4.3 , feel free to reopen if happens again
