### ISSUE TITLE
[ios]: Multiple commands produce

### ISSUE THREAD

**Issue by thevan-bic** [jerson/react-native-fast-rsa#90]
I got an issue when running the command: xcodebuild archive!

```
❌  error: Multiple commands produce '/Users/teammobile/Library/Developer/Xcode/DerivedData/app-bjmyswgopqbdlkakulhumanlxapx/Build/Intermediates.noindex/ArchiveIntermediates/app_staging/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/react_native_fast_rsa.framework/Headers/librsa_bridge.h'
```
Thanks.

**Comment by rmaharba** [comment]
Same error here!

**Comment by rmaharba** [comment]
@jerson The last PR is causing this error for the last version, also for the .3 when you use the new architecture it doesn't find the spec generated, we had to create a fork an comment the lines where it evaluates the RCT_NEW_ARCH_ENABLED, and use the bridge for the package.

**Comment by jerson** [comment]
@rmaharba  Thanks for let me know, I haven't tested using RCT_NEW_ARCH_ENABLED yet, but for the other issue I think needs some adjustments in the podspec to only select the actual source files and not the framework headers https://github.com/jerson/react-native-fast-rsa/blob/master/react-native-fast-rsa.podspec#L17

**Comment by rmaharba** [comment]
@jerson Thanks! I'll be waiting for the update, and maybe for the new architecture, just comment or disable that evaluation until you can test it.

**Comment by rmaharba** [comment]
And, sorry, but we are using the .2 not the .3, was a mistake on my comment. Because the .3 is giving the error above.

**Comment by jerson** [comment]
@rmaharba when you get some time, could you take a look to this branch #91

**Comment by rmaharba** [comment]
@jerson Thank so much for your fast response and solution for the issue!

I was testing this branch and for me works without any error while it was compiling for iOS.

For the new architecture I don't know if you're using the correct approach to generate the specs, but you need to create a TypeScript/Flow file in a js folder on your project, so codegen can find it and generate the expected specs, I can pass you the documentation here for more info:

https://github.com/reactwg/react-native-new-architecture/blob/main/docs/turbo-modules.md

**Comment by jerson** [comment]
yeah @rmaharba the code is generated now also referenced but still I need to make some code changes to remove bridge [references](https://github.com/jerson/react-native-fast-rsa/blob/master/ios/FastRsa.mm#L8-L9) in iOS so for now I'm disabling it, android at least works fine

I'm going to do additional testing today and release it later today, thank you for you help
